export const questions = {
  "Kite AI Assistant": [
    "Tell me about the latest updates in Kite AI",
    "What are the upcoming features in Kite AI?",
    "How can Kite AI improve my development workflow?",
    "What makes Kite AI unique in the market?",
    "How does Kite AI handle code completion?",
    "Can you explain Kite AI's machine learning capabilities?",
    "What programming languages does Kite AI support best?",
    "How does Kite AI integrate with different IDEs?",
    "What are the advanced features of Kite AI?",
    "How can I optimize my use of Kite AI?",
    "What are the top 100 features of Kite AI?",
    "What are the top 50 features of Kite AI?",
    "What are the top 20 features of Kite AI?",
    "What are the top 10 features of Kite AI?",
    "What are the top 5 features of Kite AI?",
    "What are the top 3 features of Kite AI?",
    "What is the top feature of Kite AI?"
  ],
  "Crypto Price Assistant": [
    "What's the current market sentiment for Solana?",
    "Analyze Bitcoin's price movement in the last hour",
    "Compare ETH and BTC performance today",
    "Which altcoins are showing bullish patterns?",
    "Market analysis for top 10 cryptocurrencies",
    "Technical analysis for Polkadot",
    "Price movement patterns for Avalanche",
    "Polygon's market performance analysis",
    "Latest developments affecting BNB price",
    "Cardano's market outlook",
    "How's the market looking for Ethereum Classic?",
    "Current market trends for Stellar",
    "Evaluate Cosmos's recent price trends",
    "Evaluate Litecoin's recent price trends",
    "Current market trends for Bitcoin Cash",
    "Analyze Chainlink's price movement in the last hour",
    "Compare Monero and ZCash performance today",
    "Market analysis for top 50 cryptocurrencies",
    "Technical analysis for EOS",
    "Price movement patterns for Binance Coin",
    "Tron's market performance analysis",
    "Latest developments affecting Dogecoin price",
    "VeChain's market outlook",
    "How's the market looking for IOTA?",
    "Current market trends for NEO",
    "Evaluate Bitcoin SV's recent price trends",
    "Analyze Ethereum's price movement in the last hour",
    "Compare Cardano and Stellar performance today",
    "Market analysis for top 100 cryptocurrencies",
    "Technical analysis for Ripple",
    "Price movement patterns for Shiba Inu",
    "Tether's market performance analysis",
    "Latest developments affecting USD Coin price",
    "Uniswap's market outlook",
    "How's the market looking for Aave?",
    "Current market trends for Terra",
    "Evaluate Solana's recent price trends"
  ],
  "Transaction Analyzer": [],
};
